[server]
follow_symlink = false
browser = "default"

[runtime]
auto_instantiate = true
default_auto_download = []
on_cell_change = "autorun"
default_sql_output = "auto"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
default_csv_encoding = "utf-8"
auto_reload = "autorun"
reactive_tests = true

[display]
cell_output = "above"
default_table_max_columns = 50
code_editor_font_size = 22
default_table_page_size = 10
dataframes = "rich"
theme = "light"
reference_highlighting = true
default_width = "full"

[package_management]
manager = "uv"

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.models]
displayed_models = []
custom_models = []
edit_model = "anthropic/claude-opus-4-6"
chat_model = "anthropic/claude-sonnet-4-5"

[ai.open_ai]

[ai.custom_providers]

[ai.google]

[ai.anthropic]
api_key = ""

[completion]
activate_on_typing = true
signature_hint_on_typing = true
copilot = "github"

[snippets]
include_default_snippets = true
custom_paths = []

[experimental]
external_agents = false

[mcp]
presets = []

[mcp.mcpServers]

[diagnostics]
sql_linter = true

[language_servers.pylsp]
enable_flake8 = false
enable_pyflakes = false
enable_pylint = false
enable_ruff = true
enabled = false
enable_pydocstyle = false
enable_mypy = true

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

[formatting]
line_length = 79
