[formatting]
line_length = 79

[ai]
rules = ""
inline_tooltip = false
mode = "manual"

[ai.anthropic]
api_key = ""

[ai.custom_providers]

[ai.google]

[ai.open_ai]

[ai.models]
custom_models = []
chat_model = "anthropic/claude-sonnet-4-5"
displayed_models = []
edit_model = "anthropic/claude-opus-4-6"

[server]
follow_symlink = false
browser = "default"

[display]
code_editor_font_size = 20
default_table_page_size = 10
default_table_max_columns = 50
reference_highlighting = true
dataframes = "rich"
theme = "light"
cell_output = "above"
default_width = "full"

[diagnostics]
sql_linter = true

[language_servers.pylsp]
enable_pylint = false
enable_ruff = true
enable_pydocstyle = false
enabled = false
enable_pyflakes = false
enable_flake8 = false
enable_mypy = true

[language_servers.ty]
enabled = false

[package_management]
manager = "uv"

[completion]
signature_hint_on_typing = true
activate_on_typing = true
copilot = "github"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[snippets]
custom_paths = []
include_default_snippets = true

[mcp]
presets = []

[mcp.mcpServers]

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

[runtime]
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
default_sql_output = "auto"
auto_reload = "autorun"
default_auto_download = []
reactive_tests = true
auto_instantiate = true
output_max_bytes = 8000000
default_csv_encoding = "utf-8"
watcher_on_save = "lazy"

[experimental]
external_agents = false
