[diagnostics]
sql_linter = true

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.anthropic]
api_key = ""

[ai.open_ai]

[ai.custom_providers]

[ai.models]
displayed_models = []
edit_model = "anthropic/claude-opus-4-6"
custom_models = []
chat_model = "anthropic/claude-sonnet-4-5"

[ai.google]

[completion]
copilot = "github"
signature_hint_on_typing = true
activate_on_typing = true

[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
default_auto_download = []
watcher_on_save = "lazy"
default_csv_encoding = "utf-8"
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
reactive_tests = true
default_sql_output = "auto"
auto_reload = "autorun"
auto_instantiate = true
output_max_bytes = 8000000

[server]
browser = "default"
follow_symlink = false

[language_servers.pylsp]
enable_pyflakes = false
enabled = false
enable_flake8 = false
enable_mypy = true
enable_pydocstyle = false
enable_ruff = true
enable_pylint = false

[display]
default_table_max_columns = 50
reference_highlighting = true
code_editor_font_size = 22
default_table_page_size = 10
default_width = "full"
dataframes = "rich"
cell_output = "above"
theme = "dark"

[formatting]
line_length = 79

[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[experimental]
external_agents = false
