[snippets]
include_default_snippets = true
custom_paths = []

[runtime]
default_sql_output = "auto"
auto_instantiate = true
output_max_bytes = 8000000
watcher_on_save = "lazy"
reactive_tests = true
default_auto_download = []
auto_reload = "autorun"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000

[completion]
activate_on_typing = true
copilot = false

[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[mcp]
presets = []

[mcp.mcpServers]

[server]
browser = "default"
follow_symlink = false

[formatting]
line_length = 79

[diagnostics]
sql_linter = true

[experimental]

[package_management]
manager = "uv"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.anthropic]

[ai.open_ai]

[ai.google]

[ai.models]
displayed_models = []
custom_models = []

[display]
cell_output = "above"
default_table_page_size = 10
dataframes = "rich"
theme = "light"
default_table_max_columns = 50
reference_highlighting = false
default_width = "full"
code_editor_font_size = 16

[language_servers.pylsp]
enable_pydocstyle = false
enable_flake8 = false
enable_mypy = true
enable_pylint = false
enable_ruff = true
enabled = false
enable_pyflakes = false
