[runtime]
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
on_cell_change = "autorun"
auto_reload = "off"
auto_instantiate = true

[package_management]
manager = "uv"

[keymap]
preset = "default"
[keymap.overrides]

[display]
dataframes = "rich"
code_editor_font_size = 16
default_width = "full"
theme = "light"
cell_output = "above"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[experimental]

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[formatting]
line_length = 79

[ai]
rules = ""
[ai.anthropic]

[ai.open_ai]

[ai.google]

[completion]
activate_on_typing = true
copilot = false
