[[session]]
name = "codebox"
path = "~/DROPBOX/REPOS/codebox"
startup_command = "~/.config/sesh/scripts/codebox.sh"

[[session]]
name = "dotfiles"
path = "~/DROPBOX/REPOS/dotfiles"
startup_command = "~/.config/sesh/scripts/dotfiles.sh"

[[session]]
name = "ss_applications"
path = "~/DROPBOX/REPOS/ss_applications"
startup_command = "~/.config/sesh/scripts/ss-applications.sh"

[[session]]
name = "ss_personal_quarto_blog"
path = "~/DROPBOX/REPOS/ss_personal_quarto_blog"
startup_command = "~/.config/sesh/scripts/ss-personal-quarto-blog.sh"

[[session]]
name = "zk"
path = "~/DROPBOX/notes/zk"
startup_command = "~/.config/sesh/scripts/zk.sh"

[[session]]
name = "rss"
path = "~/Downloads"
startup_command = "~/.config/sesh/scripts/rss.sh"
