[[session]]
name = "play"
path = "~/DROPBOX/REPOS/codebox"
startup_command = "~/.config/sesh/scripts/codebox.sh"

[[session]]
name = "dotfiles"
path = "~/DROPBOX/REPOS/dotfiles"
startup_command = "~/.config/sesh/scripts/dotfiles.sh"

[[session]]
name = "career"
path = "~/DROPBOX/REPOS/ss_applications"
startup_command = "~/.config/sesh/scripts/ss-applications.sh"

[[session]]
name = "blog"
path = "~/DROPBOX/REPOS/ss_personal_quarto_blog"
startup_command = "~/.config/sesh/scripts/blog.sh"

[[session]]
name = "notes"
path = "~/DROPBOX/notes/zk"
startup_command = "~/.config/sesh/scripts/notes.sh"

[[session]]
name = "feed"
path = "~/Downloads"
startup_command = "~/.config/sesh/scripts/feed.sh"
