# espanso configuration file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/configuration/options

toggle_key: OFF
undo_backspace: true
auto_restart: true
search_shortcut: ALT+SHIFT+SPACE
search_trigger: ";search"
backend: clipboard # important, `backend` makes injections work on macOS
show_icon: false
show_notifications: false
preserve_clipboard: true
